### ISSUE TITLE
ags not opening bar

### ISSUE THREAD

**Issue by gutteringHearthplace** [Abaan404/dotfiles#5]
Hey, was wondering if you could help me out moving to the AGS version of this repo- I had everything working a while ago, the widgets worked very well, but AGS has decided to stop working for- opaque reasons to my eye.

I've actually tried reinstalling your repo as-is without making changes, but the problem seems to be stuck now. Bun's having a difficult time compiling these days so I've been using bun-bin.

versions:

`ags -v`: `1.7.6`
`gjs --version`: `1.78.4`
`bun -v`: `1.0.26` 

ags warning generated on startup:

```
(com.github.Aylur.ags:61228): Gjs-WARNING **: 13:05:03.843: Unhandled promise rejection. To suppress this warning, add an error handler to your promise chain with .catch() or a try-catch block around your await expression. Stack trace of the failed promise:
  _load@resource:///com/github/Aylur/ags/app.js:153:16
  vfunc_activate@resource:///com/github/Aylur/ags/app.js:93:14
  _init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
```

When I run the js command you've set up to toggle the bar, I get the following: 
```
ags -r "toggle(\"bar\")"
ReferenceError: toggle is not defined
```

**Comment by Abaan404** [comment]
Thats odd, can you check if running
```sh
bun build ~/.config/ags/ts/main.ts --outdir /tmp/ags/js --external "resource:///*" --external "gi://*" --external "cairo"
```
works and creates the `/tmp/ags/js/main.js` file?

**Comment by gutteringHearthplace** [comment]
It does.

**Comment by gutteringHearthplace** [comment]
[main.js.txt](https://github.com/Abaan404/dotfiles/files/14320259/main.js.txt)

**Comment by Abaan404** [comment]
The stacktrace points to the ags library's [_load()](https://github.com/Aylur/ags/blob/785f1a941a52c32d1cbe77a5eb935713fe45cddb/src/app.ts#L217) function failing somehow. Is there any other log issued with it since I'm unable to reproduce that error/warning.

Last thing you can check is if a `~/.config/ags/config.js` exists and is the same file as `~/.dotfiles/config/ags/config.js` after you run the reload script (Super+H or `~/.dotfiles/scripts/reload.py`), otherwise you might wanna check with people on ags's discord for more help since it seems to be an ags issue

**Comment by gutteringHearthplace** [comment]
Stale- just switched to using waybar, plus I can't reproduce on the new NixOS install
